apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  selector:
    matchLabels:
      app: main
  replicas: 2
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: 23emre/main:latest
        ports:
        - containerPort: 11130